
name: CI
# TODO: which branch do we need this action https://gist.github.com/cecilemuller/437d7340b9f095cf5635dc9780a05092
on: [push]
jobs:
  build:
    timeout-minutes: 10
    name: Build check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: yarn install, build
        run: |
          yarn install
          yarn build
        env:
          CI: true