name: CI
on: [push]
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        token: ${{ github.token }}
        filters: .github/workflows/filters.yml

    - name: Cloudflare pages build
      if: steps.filter.outputs.cfpage == 'true'
      # TODO: which branch do we need this action https://gist.github.com/cecilemuller/437d7340b9f095cf5635dc9780a05092
      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
        - name: yarn install, build
          run: |
            yarn install
            yarn build
          env:
            CI: true